[package]
name = "aoc-2021"
version = "0.1.0"
authors = ["Ghassan Achi <ghassan.achi@gmail.com>"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
prettytable-rs = "^0.8"
itertools = "0.10.2"
colored = "2"

